config/routes.rb
Rails.application.routes.draw do

  # Error handling
  %w(404 422 500).each do |code|
    get code, :to => "errors#show", :code => code
  end

  devise_for :users

  # Rails admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Ckeditor
  mount Ckeditor::Engine => '/ckeditor'
  
  # Comments
  authenticate :user, ->(user) { user.has_role?(:admin)} do
    get "task_comments/unread", :to => "task_comments#unread", :as => "task_comments_unread"
    post "task_comments/mark_as_read", :to => "task_comments#mark_as_read", :as => "task_comments_mark_as_read"
  end

  # Tasks
  authenticate :user, ->(user) { user.has_role?(:admin)} do
    get "gantt", :to => "gantt#index", :as => "gantt"
    get "gantt/data", :to => "gantt#data", :as => "gantt_data"
    # delete "task/:id", :to => "tasks#delete", :as => "task_delete"
    # get "task/:id/comments", :to => "tasks#comments", :as => "task_get_comments"
    patch "tasks/update_batch", :to => "tasks#update_batch", :as => "task_update_batch"
    resources :users
    resources :gantt
    resources :projects
    resources :task_links
    resources :tasks, :shallow => true, :constraints => { } do
      resources :task_comments, path: 'comments'
      resources :task_attachments, path: 'attachments'
    end
  end

  # Users
  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    # post '/signup' => 'registrations#new', :as => :new_user_registration 
    get "/profile/edit" => "devise/registrations#edit"
    get "/login" => "devise/sessions#new", :as => :login
    get "/logout" => "devise/sessions#destroy"
  end

  # Root
  root to: "pages#show", :slug => "home"

  # Posts
  resources :posts, path: 'blog', param: :slug
  # get '/blog' => 'posts#index', :as => 'blog'
  # get '/blog/:slug' => 'posts#show', :as => 'post'
  # get '/blog/:slug/edit' => 'posts#edit', :as => 'edit_post'
  # patch '/blog/:slug/update' => 'posts#update', :as => 'update_post'

  # Portfolio
  get '/portfolio' => 'portfolios#index', :as => 'portfolio'
  get '/portfolio/:slug' => 'portfolios#show', :as => 'show_portfolio'
  get '/portfolio/:slug/edit' => 'portfolios#edit', :as => 'edit_portfolio'
  patch '/portfolio/:slug/update' => 'portfolios#update', :as => 'update_portfolio'

  # Contact / messages
  post '/contact' => 'messages#create', :as => 'messages'

  # Pages
  get '/' => 'pages#show', :slug => 'home', :as => 'home'
  get '/:slug/edit' => 'pages#edit', :as => 'edit_page', :constraints => {:slug => /.*/}
  patch '/:slug/update' => 'pages#update', :as => 'update_page', :constraints => {:slug => /.*/}
  get '/:slug' => 'pages#show', :constraints => {:slug => /.*/}, :as => 'page'


end

app/models/task_attachment.rb
class TaskAttachment < ActiveRecord::Base
	belongs_to :task
	has_attached_file :file,
	  :path => ":rails_root/public/files/task_attachments/:id/:filename",
	  :url  => "/files/task_attachments/:id/:filename",
	  :styles => { thumb: "150x100#" }
	do_not_validate_attachment_file_type :file
	validates_presence_of :file, :task_id

end

app/controllers/task_attachments_controller.rb
class TaskAttachmentsController < ApplicationController
	protect_from_forgery

	# GET /attachments/:id
	def show
		@task_attachment = TaskAttachment.find(params[:id])
		send_file assets_dir + @task_attachment.file.url(:original, false)
	end

	# GET /tasks/:task_id/attachments
	def index
	  @task_attachments = TaskAttachment.where(params[:task_id])
	end

	# POST /attachments/:task_id
	def create
	@task_attachment = TaskAttachment.new(task_attachment_params)

	  respond_to do |format|
	    if @task_attachment.save
 	  	  format.js {  flash[:success] = "Attachment uploaded successfully" }
	      format.html { redirect_to @task_attachment, notice: 'Attachment was successfully uploaded.' }
	      format.json { render json: @task_attachment, status: :created, location: @task_attachment }
	    else
 	  	  format.js {  flash[:error] = "Error uploading attachment" }
	      format.html { render action: "new" }
	      format.json { render json: @task_attachment.errors, status: :unprocessable_entity }
	    end
	  end
	end

	def destroy
	  @task_attachment = TaskAttachment.find(params[:id])
	  respond_to do |format|
		  if @task_attachment.destroy    
		  	format.js {  flash[:success] = "Attachment deleted" }
		  else
		  	format.js {  flash[:error] = @task_attachment.errors.full_messages.join(',') }
		  end
	  end
	end

	private
		def task_attachment_params
		  params.require(:task_attachment).permit(:file, :task_id)
		end

end

app/helpers/task_attachments_helper.rb
module TaskAttachmentsHelper
end

app/views/task_attachments/_form.html.erb
<%= simple_form_for [@task, @task_attachment], remote: true, html: { class: 'dropzone', multipart: true } do |f| %>
  <%= f.input :file, as: :file %>
  <%= f.input :task_id, :as => :hidden, :input_html => { :value => @task.id } %>
  <%= f.button :submit %>
<% end %>

app/views/task_attachments/_index.html.erb
<div class="task-attachments" id="task-attachments">
	<div class="task-attachments-previews dropzone-previews" id="task-attachments-previews">
	  <% @task.attachments.each do |attachment| %>
	  	<div class="task-attachment" id="task-attachment-<%= attachment.id %>">
	  		<div class="task-attachment-info">
		  		<%= image_tag attachment.file.url(:thumb), :class => "tooltipped", :data => { :position => 'left', :tooltip => attachment.file.original_filename } %>
		  		<%#= attachment.file.original_filename %>
	  		</div>
	  		<div class="task-attachment-actions">
	  			<%= link_to '<i class="ion-ios-cloud-download"></i>'.html_safe, task_attachment_path(attachment.id), :class => 'task-attachment-download' %>
	  			<%#= link_to 'Copy URL', attachment.file.url %>
	  			<%= link_to '<i class="ion-close-circled"></i>'.html_safe, task_attachment_path(attachment.id), data: {:confirm => 'Are you sure you want to permanently delete this attachment?'}, :method => :delete, :remote => true, :class => 'task-attachment-delete' %>
	  		</div>
	  	</div>
	  <% end %>
	  <%= render 'task_attachments/form' %>
  	</div>
</div>

app/views/task_attachments/create.js.erb
<% flash.each do |name, msg| %>
  <% @message = content_tag :div, msg, class: "alert alert-fixed alert-" + name %>
<% end %>
$('#notifications').html("<%= escape_javascript @message %>");

app/views/task_attachments/destroy.js.erb
<% flash.each do |name, msg| %>
  <% @message = content_tag :div, msg, class: "alert alert-fixed alert-" + name %>
<% end %>
$('#task-attachment-<%= @task_attachment.id %>').remove();
$('#notifications').html("<%= escape_javascript @message %>");