config/routes.rb
Rails.application.routes.draw do

  # Error handling
  %w(404 422 500).each do |code|
    get code, :to => "errors#show", :code => code
  end

  devise_for :users

  # Rails admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Ckeditor
  mount Ckeditor::Engine => '/ckeditor'
  
  # Comments
  authenticate :user, ->(user) { user.has_role?(:admin)} do
    get "task_comments/unread", :to => "task_comments#unread", :as => "task_comments_unread"
    post "task_comments/mark_as_read", :to => "task_comments#mark_as_read", :as => "task_comments_mark_as_read"
  end

  # Tasks
  authenticate :user, ->(user) { user.has_role?(:admin)} do
    get "gantt", :to => "gantt#index", :as => "gantt"
    get "gantt/data", :to => "gantt#data", :as => "gantt_data"
    # delete "task/:id", :to => "tasks#delete", :as => "task_delete"
    # get "task/:id/comments", :to => "tasks#comments", :as => "task_get_comments"
    patch "tasks/update_batch", :to => "tasks#update_batch", :as => "task_update_batch"
    resources :users
    resources :gantt
    resources :projects
    resources :task_links
    resources :tasks, :shallow => true, :constraints => { } do
      resources :task_comments, path: 'comments'
      resources :task_attachments, path: 'attachments'
    end
  end

  # Users
  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    # post '/signup' => 'registrations#new', :as => :new_user_registration 
    get "/profile/edit" => "devise/registrations#edit"
    get "/login" => "devise/sessions#new", :as => :login
    get "/logout" => "devise/sessions#destroy"
  end

  # Root
  root to: "pages#show", :slug => "home"

  # Posts
  resources :posts, path: 'blog', param: :slug
  # get '/blog' => 'posts#index', :as => 'blog'
  # get '/blog/:slug' => 'posts#show', :as => 'post'
  # get '/blog/:slug/edit' => 'posts#edit', :as => 'edit_post'
  # patch '/blog/:slug/update' => 'posts#update', :as => 'update_post'

  # Portfolio
  get '/portfolio' => 'portfolios#index', :as => 'portfolio'
  get '/portfolio/:slug' => 'portfolios#show', :as => 'show_portfolio'
  get '/portfolio/:slug/edit' => 'portfolios#edit', :as => 'edit_portfolio'
  patch '/portfolio/:slug/update' => 'portfolios#update', :as => 'update_portfolio'

  # Contact / messages
  post '/contact' => 'messages#create', :as => 'messages'

  # Pages
  get '/' => 'pages#show', :slug => 'home', :as => 'home'
  get '/:slug/edit' => 'pages#edit', :as => 'edit_page', :constraints => {:slug => /.*/}
  patch '/:slug/update' => 'pages#update', :as => 'update_page', :constraints => {:slug => /.*/}
  get '/:slug' => 'pages#show', :constraints => {:slug => /.*/}, :as => 'page'


end

app/models/task_comment.rb
class TaskComment < ActiveRecord::Base
	validates_presence_of :content, :task_id
	belongs_to :user
	belongs_to :task
	acts_as_readable :on => :created_at
	default_scope { order(created_at: :desc) }
	scope :unread_by_user, ->(user) { where.not(user_id: user.id).unread_by(user) }

end

app/controllers/task_comments_controller.rb
class TaskCommentsController < ApplicationController
  before_action :set_task_comment, only: [:show, :edit, :update, :destroy]

  # GET /task_comments/1/edit
  def edit
  end

  # GET /task_comments/unread
  def unread
    @task_comments = TaskComment.unread_by_user(current_user)
    respond_to do |format|
      format.html { render :partial => 'unread' }
      format.js   { render layout: false, content_type: 'text/javascript' }
    end
  end

  # POST /task_comments/mark_as_read
  def mark_as_read
    TaskComment.where(id: params[:ids]).mark_as_read! :all, :for => current_user
  end

  # POST /task_comments
  # POST /task_comments.json
  def create
    @task_comment = TaskComment.new(task_comment_params)
    @task_comment.user_id = current_user.id

    respond_to do |format|
      if @task_comment.save
        if params.has_key?(:email_to) && !params[:email_to].blank?
          TaskMailer.email_comment(@task_comment, params[:email_to]).deliver_now
        end
        format.html { redirect_to @task_comment, notice: 'Task comment was successfully created.' }
        format.js   { render layout: false, content_type: 'text/javascript' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /task_comments/1
  # PATCH/PUT /task_comments/1.json
  def update
    respond_to do |format|
      if @task_comment.update(task_comment_params)
        format.html { redirect_to @task_comment, notice: 'Task comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_comment }
      else
        format.html { render :edit }
        format.json { render json: @task_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_comments/1
  # DELETE /task_comments/1.json
  def destroy
    @task_comment.destroy
    respond_to do |format|
      format.html { redirect_to task_comments_url, notice: 'Task comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_comment
      @task_comment = TaskComment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_comment_params
      params.fetch(:task_comment, {})
      params.permit(:content, :task_id)
    end
end

app/helpers/task_comments_helper.rb
module TaskCommentsHelper
end

app/views/task_comments/_comment.html.erb
<div class="task-comment <%= 'current-user' if comment.user == current_user %> <%= 'unread' if comment.user != current_user && comment.unread?(current_user) %>">
  	<div class="avatar">
	  	<a class="tooltipped" data-position="bottom" data-delay="50" data-tooltip="<%= comment.user.name %>">
		  	<%= raw comment.user.avatar('medium') %>
	  	</a>
  	</div>
  	<div class="task-comment-content">
	  	<%= comment.content %>
  	</div>
  	<div class="task-comment-date">
  		<%= l comment.created_at %>
  	</div>
  	<%#= link_to 'Delete', task_comment_path(:id => comment.id), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/task_comments/_form.html.erb
<%= simple_form_for [@task, @task_comment], remote: true do |f| %>
  <%= f.error_notification %>

  <div class="input-field">
  	<%= text_area_tag "content", @task_comment.content, class: "materialize-textarea", placeholder: "Enter your comment" %>
  </div>
  <div class="row">
    <div class="col m8">
      <input name="email_to" class="email_to" id="email_to" placeholder="Email to" data-options="<%= @users.to_json %>" />
    </div>
    <div class="col m4">
      <div class="form-actions">
        <span class="btn rounded" id="attachment-add"><i class="ion-android-attach"></i></span>
        <%= f.button :submit, :value => 'Send' %>
      </div>
    </div>
  </div>


<% end %>

app/views/task_comments/_index.html.erb
<%= render 'task_comments/form' %>

<div class="task-comments" id="task-comments">
  <% @task_comments.each do |comment| %>
    <%= render 'task_comments/comment', :comment => comment %>
  <% end %>
</div>

<% if @unread_comments.any? %>
	<script>
	$.ajax({
	  type: "POST",
	  url: "<%= task_comments_mark_as_read_path %>",
	  data: { ids: <%= @unread_comments %> },
	  success: function(html){
	  }
	  });
	</script>
<% end %>

app/views/task_comments/_unread.html.erb
<div class="task-comments unread">
	<% @task_comments.each do |comment| %>
		<%= comment.content %>
	<% end %>
</div>

app/views/task_comments/create.js.erb
// Insert newly added comment
var comment = $("<%= escape_javascript( render 'task_comments/comment', :comment => @task_comment ) %>").hide().fadeIn(300);
$("#task-comments").prepend(comment);
 
// Empty form
$('#new_task_comment')[0].reset();

app/views/task_comments/edit.html.erb
<h1>Editing Task Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_comment %> |
<%= link_to 'Back', task_comments_path %>

app/views/task_comments/indexdeleteafter.js.erb
alert('test');

app/views/task_comments/new.html.erb
<h1>New Task Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', task_comments_path %>

app/views/task_comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_task_comment_path(@task_comment) %> |
<%= link_to 'Back', task_comments_path %>