config/routes.rb
Rails.application.routes.draw do

  # Error handling
  %w(404 422 500).each do |code|
    get code, :to => "errors#show", :code => code
  end

  devise_for :users

  # Rails admin
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Ckeditor
  mount Ckeditor::Engine => '/ckeditor'
  
  # Comments
  authenticate :user, ->(user) { user.has_role?(:admin)} do
    get "task_comments/unread", :to => "task_comments#unread", :as => "task_comments_unread"
    post "task_comments/mark_as_read", :to => "task_comments#mark_as_read", :as => "task_comments_mark_as_read"
  end

  # Tasks
  authenticate :user, ->(user) { user.has_role?(:admin)} do
    get "gantt", :to => "gantt#index", :as => "gantt"
    get "gantt/data", :to => "gantt#data", :as => "gantt_data"
    # delete "task/:id", :to => "tasks#delete", :as => "task_delete"
    # get "task/:id/comments", :to => "tasks#comments", :as => "task_get_comments"
    patch "tasks/update_batch", :to => "tasks#update_batch", :as => "task_update_batch"
    resources :users
    resources :gantt
    resources :projects
    resources :task_links
    resources :tasks, :shallow => true, :constraints => { } do
      resources :task_comments, path: 'comments'
      resources :task_attachments, path: 'attachments'
    end
  end

  # Users
  devise_scope :user do
    get "/signup" => "devise/registrations#new"
    # post '/signup' => 'registrations#new', :as => :new_user_registration 
    get "/profile/edit" => "devise/registrations#edit"
    get "/login" => "devise/sessions#new", :as => :login
    get "/logout" => "devise/sessions#destroy"
  end

  # Root
  root to: "pages#show", :slug => "home"

  # Posts
  resources :posts, path: 'blog', param: :slug
  # get '/blog' => 'posts#index', :as => 'blog'
  # get '/blog/:slug' => 'posts#show', :as => 'post'
  # get '/blog/:slug/edit' => 'posts#edit', :as => 'edit_post'
  # patch '/blog/:slug/update' => 'posts#update', :as => 'update_post'

  # Portfolio
  get '/portfolio' => 'portfolios#index', :as => 'portfolio'
  get '/portfolio/:slug' => 'portfolios#show', :as => 'show_portfolio'
  get '/portfolio/:slug/edit' => 'portfolios#edit', :as => 'edit_portfolio'
  patch '/portfolio/:slug/update' => 'portfolios#update', :as => 'update_portfolio'

  # Contact / messages
  post '/contact' => 'messages#create', :as => 'messages'

  # Pages
  get '/' => 'pages#show', :slug => 'home', :as => 'home'
  get '/:slug/edit' => 'pages#edit', :as => 'edit_page', :constraints => {:slug => /.*/}
  patch '/:slug/update' => 'pages#update', :as => 'update_page', :constraints => {:slug => /.*/}
  get '/:slug' => 'pages#show', :constraints => {:slug => /.*/}, :as => 'page'


end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  belongs_to :category, :class_name => 'PostCategory', :foreign_key => 'post_category_id'
  has_attached_file :image, styles: { full: "1920>", medium: "340x600#" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates_presence_of :title, :content
  default_scope { order('created_at DESC') }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  after_filter { flash.discard if request.xhr? }
  protect_from_forgery
  layout "frontend"
  

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(:is_published => true).page params[:page]
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if (!@post.is_published)
      authorize! :show, @post
    end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    authorize! :edit, @post
    render layout: "live_edit"
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    authorize! :update, @post
    respond_to do |format|
      if @post.update(post_params)
        format.js {  flash[:success] = "Post updated!" }
        else
        format.js {  flash[:error] = "Error" }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  # def destroy
  #   @post.destroy
  #   respond_to do |format|
  #     format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      if current_user && current_user.has_role?(:admin)
        @post = Post.includes(:user, :category).find_by_slug!(params[:slug])
      else
        @post = Post.includes(:user, :category).find_by_slug!(params[:slug])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post, {})
      params.permit(:content)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<% body_class 'post-single header-light-active live-editor' %>
<% title @post.title %>

<div class="page-header full-browser-height section-dark" id="post-page-header">
	<div class="parallax"><img src="<%= @post.image %>"></div>
</div>

<div class="container">
	<div class="row">
		<div class="col l8 post-content">
		<div class="post-meta">
			<% if @post.category %>
			    <span class="post-category h5">
			        In <%= @post.category.name %>,
			    </span>
			<% end %>
			<% if @post.user %>
			    <span class="post-author h5">
			        By <%= @post.user.name %>
			    </span>
			<% end %>
		</div>

		  <h1 class="text-center"><%= @post.title %></h1>
		  <div class="editor" id="editor" contenteditable="true">
		  	<%= raw @post.content %>
		  </div>
		</div>
		<div class="col l4">
		  <div class="parallax-layer">
		  	<h5 class="rotated-text post-date"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col l8">
		    <%= render 'layouts/social_share' %>
		</div>
		<div class="col l4">
			<a href="<%= posts_path %>" class="blog-back-link">Back to blog</a>
		</div>
	</div>
</div>

<%= render 'layouts/live_editor_controls', :update_path => post_path %>

app/views/posts/index.html.erb
<% title 'Blog' %>
<% body_class 'blog' %>

<div class="container">
    <h1>Blog</h1>
</div>

<div class="container">
  <% @posts.each do |post| %>
    <article class="post col m12">
        <div class="row">
            <svg viewbox="0 0 200 100" class="has-animation has-animation-out svg-frame reanimate" data-animation-delay="500">
              <line x1="200" y1="0" x2="0" y2="0" class="line1" />
              <line x1="195" y1="105" x2="195" y2="30" class="line2" />
              <line x1="0" y1="100" x2="200" y2="100" class="line3" />
              <line x1="5" y1="-5" x2="5" y2="70" class="line4" />
            </svg>
            <div class="col m6">
                <div class="post-img">
                    <div class="post-date rotated-text h5"><%= post.created_at.strftime("%b %d, %Y") %></div>
                    <% if !post.image.blank? %>
                        <%= image_tag post.image(:medium) %>
                    <% end %>
                </div>
            </div>
            <div class="col m6 post-meta">
                <% if post.category %>
                    <div class="post-category h5">
                        In <%= post.category.name %>
                    </div>
                <% end %>
                <% if post.user %>
                    <div class="post-author h5">
                        By <%= post.user.name %>
                    </div>
                <% end %>
                <h3 class="post-title"><%= link_to post.title, post_path(:slug => post.slug) %></h3>
                <div class="post-desc">
                    <%= post.description %>
                </div>
                <div class="post-read-more">
                    <%= link_to 'Read more', post_path(:slug => post.slug) %>
                </div>
            </div>
            <div class="long-arrow"></div>
        </div>
    </article>
  <% end %>
  <%= paginate @posts %>
</div>

app/views/posts/show.html.erb
<% body_class 'post-single header-light-active' %>
<% title @post.title %>

<div class="page-header full-browser-height section-dark" id="post-page-header">
	<div class="parallax"><img src="<%= @post.image %>"></div>
</div>

<div class="container">
	<div class="row">
		<div class="col l8 post-content">
		<div class="post-meta">
			<% if @post.category %>
			    <span class="post-category h5">
			        In <%= @post.category.name %>,
			    </span>
			<% end %>
			<% if @post.user %>
			    <span class="post-author h5">
			        By <%= @post.user.name %>
			    </span>
			<% end %>
		</div>

		  <h1 class="text-center"><%= @post.title %></h1>
		  <div><%= raw @post.content %></div>
		</div>
		<div class="col l4">
		  <div class="parallax-layer">
		  	<h5 class="rotated-text post-date"><%= @post.created_at.strftime('%b %d, %Y') %></h5>
		  </div>
		</div>
	</div>
	<div class="row">
		<div class="col l8">
		    <%= render 'layouts/social_share' %>
		</div>
		<div class="col l4">
			<a href="<%= posts_path %>" class="blog-back-link">Back to blog</a>
		</div>
	</div>
</div>

app/views/posts/update.js.erb
<% flash.each do |name, msg| %>
  <% @message = content_tag :div, raw(msg), class: "alert alert-fixed alert-" + name %>
<% end %>
$('#notifications').html("<%= escape_javascript @message %>");